apiVersion: argocd-image-updater.argoproj.io/v1alpha1
kind: ImageUpdater
metadata:
  name: demo-todo-app-updater
  namespace: argocd

spec:
  interval: 2m

  images:
    - name: docker.io/zinlinhtetdevops/demo-todo-app
      updateStrategy: newest-build
      allowTags: regexp:^[a-f0-9]{40}$

  writeBackMethod: git

  git:
    credentials: secret:argocd/git-creds

  applications:
    - demo-todo-app