apiVersion: argocd-image-updater.argoproj.io/v1alpha1
kind: ImageUpdater
metadata:
  name: demo-todo-app-updater
  namespace: argocd
spec:
  applicationRefs:
    - namePattern: "demo-todo-app"
      images:
        - alias: "todo-app"
          imageName: "docker.io/zinlinhtetdevops/demo-todo-app"
          commonUpdateSettings:
            updateStrategy: "name"
            allowTags: "regexp:^[a-f0-9]+$"
      writeBackConfig:
        method: "git:secret:argocd/git-creds"
        gitConfig:
          branch: "main"
          writeBackTarget: "file:manifests/app/deploy.yml"