apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: demo-todo-app
  namespace: argocd
  annotations:
    argocd-image-updater.argoproj.io/image-list: todo-app=docker.io/frandisharing/demo-todo-app
    argocd-image-updater.argoproj.io/todo-app.update-strategy: latest
    argocd-image-updater.argoproj.io/todo-app.helm.image-name: image.repository
    argocd-image-updater.argoproj.io/todo-app.helm.image-tag: image.tag
    argocd-image-updater.argoproj.io/write-back-method: git
spec:
  project: default
  source:
    repoURL: 'https://github.com/frandi-devops-learn/demo-todo-app-K8s.git'
    targetRevision: main
    path: manifests/app
  destination:
    server: 'https://kubernetes.default.svc'
    namespace: demo-todo
  syncPolicy:
    automated:
      prune: false
      selfHeal: true
    syncOptions:
      - CreateNamespace=true