apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: demo-todo-app
  namespace: argocd
  annotations:
    argocd-image-updater.argoproj.io/image-list: todo-app=docker.io/zinlinhtetdevops/demo-todo-app
    argocd-image-updater.argoproj.io/todo-app.update-strategy: newest-build
    argocd-image-updater.argoproj.io/todo-app.allow-tags: regexp:^[a-f0-9]+$
    argocd-image-updater.argoproj.io/write-back-method: git
    argocd-image-updater.argoproj.io/git-credentials: secret:argocd/git-creds
spec:
  project: default
  source:
    repoURL: 'https://github.com/frandi-devops-learn/demo-todo-app-K8s.git'
    targetRevision: main
    path: manifests/app
  destination:
    server: 'https://kubernetes.default.svc'
    namespace: demo-todo
  syncPolicy:
    automated:
      prune: false
      selfHeal: true
    syncOptions:
      - CreateNamespace=true