config:
  applicationsAPIKind: kubernetes
  registries:
    - name: Docker Hub
      prefix: docker.io
      api_url: https://registry-1.docker.io
      credentials: secret:argocd/dockerhub-secret
      default: true

  git:
    credentials: secret:argocd/git-creds

extraArgs:
  - --loglevel=info

rbac:
  enabled: true

serviceAccount:
  create: true
  name: argocd-image-updater